// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"time"

	"github.com/google/uuid"
	"github.com/greenpos/backend/internal/model"
)

type AuthPayload struct {
	Token string      `json:"token"`
	User  *model.User `json:"user"`
}

type CreateBranchInput struct {
	TenantID uuid.UUID `json:"tenantId"`
	Name     string    `json:"name"`
	Address  *string   `json:"address,omitempty"`
	Phone    *string   `json:"phone,omitempty"`
}

type CreateCategoryInput struct {
	BranchID    uuid.UUID `json:"branchId"`
	Name        string    `json:"name"`
	Description *string   `json:"description,omitempty"`
	SortOrder   *int      `json:"sortOrder,omitempty"`
}

type CreateOrderInput struct {
	BranchID      uuid.UUID              `json:"branchId"`
	TableID       *uuid.UUID             `json:"tableId,omitempty"`
	UserID        uuid.UUID              `json:"userId"`
	CustomerName  *string                `json:"customerName,omitempty"`
	CustomerPhone *string                `json:"customerPhone,omitempty"`
	Notes         *string                `json:"notes,omitempty"`
	Items         []CreateOrderItemInput `json:"items"`
}

type CreateOrderItemInput struct {
	ProductID uuid.UUID `json:"productId"`
	Quantity  int       `json:"quantity"`
	Notes     *string   `json:"notes,omitempty"`
}

type CreateProductInput struct {
	BranchID        uuid.UUID  `json:"branchId"`
	CategoryID      *uuid.UUID `json:"categoryId,omitempty"`
	Name            string     `json:"name"`
	Description     *string    `json:"description,omitempty"`
	Price           float64    `json:"price"`
	ImageURL        *string    `json:"imageUrl,omitempty"`
	IsAvailable     *bool      `json:"isAvailable,omitempty"`
	IsFeatured      *bool      `json:"isFeatured,omitempty"`
	PreparationTime *int       `json:"preparationTime,omitempty"`
	Allergens       []string   `json:"allergens,omitempty"`
}

type CreateReservationInput struct {
	BranchID        uuid.UUID  `json:"branchId"`
	TableID         *uuid.UUID `json:"tableId,omitempty"`
	CustomerName    string     `json:"customerName"`
	CustomerPhone   *string    `json:"customerPhone,omitempty"`
	CustomerEmail   *string    `json:"customerEmail,omitempty"`
	GuestCount      int        `json:"guestCount"`
	ReservationDate string     `json:"reservationDate"`
	ReservationTime time.Time  `json:"reservationTime"`
	Notes           *string    `json:"notes,omitempty"`
}

type CreateTableInput struct {
	BranchID uuid.UUID `json:"branchId"`
	Number   string    `json:"number"`
	Capacity *int      `json:"capacity,omitempty"`
}

type CreateTenantInput struct {
	Name     string     `json:"name"`
	Slug     string     `json:"slug"`
	Settings model.JSON `json:"settings,omitempty"`
}

type CreateUserInput struct {
	BranchID uuid.UUID      `json:"branchId"`
	Email    string         `json:"email"`
	Password string         `json:"password"`
	Name     string         `json:"name"`
	Role     model.UserRole `json:"role"`
}

type DailySales struct {
	Date    string  `json:"date"`
	Orders  int     `json:"orders"`
	Revenue float64 `json:"revenue"`
}

type DashboardMetrics struct {
	TotalOrders     int          `json:"totalOrders"`
	TotalRevenue    float64      `json:"totalRevenue"`
	AverageTicket   float64      `json:"averageTicket"`
	OrdersToday     int          `json:"ordersToday"`
	RevenueToday    float64      `json:"revenueToday"`
	OrdersThisWeek  int          `json:"ordersThisWeek"`
	RevenueThisWeek float64      `json:"revenueThisWeek"`
	TopProducts     []TopProduct `json:"topProducts"`
}

type PaymentMethodRevenue struct {
	Method  string  `json:"method"`
	Revenue float64 `json:"revenue"`
	Count   int     `json:"count"`
}

type RevenueReport struct {
	Period          string                 `json:"period"`
	TotalRevenue    float64                `json:"totalRevenue"`
	TotalOrders     int                    `json:"totalOrders"`
	AverageTicket   float64                `json:"averageTicket"`
	ByPaymentMethod []PaymentMethodRevenue `json:"byPaymentMethod"`
}

type StatusCount struct {
	Status string `json:"status"`
	Count  int    `json:"count"`
}

type Table struct {
	ID           uuid.UUID         `json:"id"`
	Branch       *model.Branch     `json:"branch"`
	Number       string            `json:"number"`
	Capacity     int               `json:"capacity"`
	Status       model.TableStatus `json:"status"`
	CurrentOrder *model.Order      `json:"currentOrder,omitempty"`
	CreatedAt    time.Time         `json:"createdAt"`
	UpdatedAt    time.Time         `json:"updatedAt"`
}

type TopProduct struct {
	ProductID    string  `json:"productId"`
	ProductName  string  `json:"productName"`
	QuantitySold int     `json:"quantitySold"`
	Revenue      float64 `json:"revenue"`
}
