package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/greenpos/backend/internal/model"
	"github.com/greenpos/backend/internal/service"
)

func intPtr(i int) *int {
	return &i
}

// Tenant is the resolver for the tenant field.
func (r *branchResolver) Tenant(ctx context.Context, obj *model.Branch) (*model.Tenant, error) {
	return r.Services.Tenant.GetByID(ctx, obj.TenantID)
}

// Users is the resolver for the users field.
func (r *branchResolver) Users(ctx context.Context, obj *model.Branch) ([]model.User, error) {
	return r.Services.User.GetByBranch(ctx, obj.ID)
}

// Categories is the resolver for the categories field.
func (r *branchResolver) Categories(ctx context.Context, obj *model.Branch) ([]model.Category, error) {
	return r.Services.Category.GetByBranch(ctx, obj.ID)
}

// Products is the resolver for the products field.
func (r *branchResolver) Products(ctx context.Context, obj *model.Branch) ([]model.Product, error) {
	return r.Services.Product.GetByBranch(ctx, obj.ID)
}

// Tables is the resolver for the tables field.
func (r *branchResolver) Tables(ctx context.Context, obj *model.Branch) ([]Table, error) {
	tables, err := r.Services.Table.GetByBranch(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	return convertTablesToGraphQL(tables, nil)
}

// Orders is the resolver for the orders field.
func (r *branchResolver) Orders(ctx context.Context, obj *model.Branch) ([]model.Order, error) {
	return r.Services.Order.GetByBranch(ctx, obj.ID)
}

// Reservations is the resolver for the reservations field.
func (r *branchResolver) Reservations(ctx context.Context, obj *model.Branch) ([]model.Reservation, error) {
	return r.Services.Reservation.GetByBranch(ctx, obj.ID)
}

// Branch is the resolver for the branch field.
func (r *categoryResolver) Branch(ctx context.Context, obj *model.Category) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, obj.BranchID)
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category) ([]model.Product, error) {
	return r.Services.Product.GetByCategory(ctx, obj.BranchID, obj.ID)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, branchID uuid.UUID) (*AuthPayload, error) {
	user, _, _, err := r.Services.Auth.Login(ctx, branchID, email, password)
	if err != nil {
		return nil, err
	}
	return &AuthPayload{
		Token: "",
		User:  user,
	}, nil
}

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input CreateTenantInput) (*model.Tenant, error) {
	return r.Services.Tenant.Create(ctx, input.Name, input.Slug)
}

// UpdateTenant is the resolver for the updateTenant field.
// FIX: removed Logo field - schema only has name and settings
func (r *mutationResolver) UpdateTenant(ctx context.Context, id uuid.UUID, name *string, settings *model.JSON) (*model.Tenant, error) {
	return r.Services.Tenant.Update(ctx, id, name, nil, settings, nil)
}

// CreateBranch is the resolver for the createBranch field.
func (r *mutationResolver) CreateBranch(ctx context.Context, input CreateBranchInput) (*model.Branch, error) {
	address := ""
	phone := ""
	if input.Address != nil {
		address = *input.Address
	}
	if input.Phone != nil {
		phone = *input.Phone
	}
	return r.Services.Branch.Create(ctx, input.TenantID, input.Name, address, phone)
}

// UpdateBranch is the resolver for the updateBranch field.
func (r *mutationResolver) UpdateBranch(ctx context.Context, id uuid.UUID, name *string, address *string, phone *string) (*model.Branch, error) {
	existing, err := r.Services.Branch.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	branchName := existing.Name
	branchAddress := existing.Address
	branchPhone := existing.Phone
	if name != nil {
		branchName = *name
	}
	if address != nil {
		branchAddress = *address
	}
	if phone != nil {
		branchPhone = *phone
	}
	return r.Services.Branch.Update(ctx, id, branchName, branchAddress, branchPhone, existing.IsActive)
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input CreateUserInput) (*model.User, error) {
	return r.Services.User.Create(ctx, input.BranchID, input.Email, input.Password, input.Name, input.Role)
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, name *string, role *model.UserRole, isActive *bool) (*model.User, error) {
	nameVal := ""
	if name != nil {
		nameVal = *name
	}
	return r.Services.User.Update(ctx, id, nameVal, role, isActive)
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.Services.User.Delete(ctx, id)
	return err == nil, err
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input CreateCategoryInput) (*model.Category, error) {
	description := ""
	sortOrder := 0
	if input.Description != nil {
		description = *input.Description
	}
	if input.SortOrder != nil {
		sortOrder = *input.SortOrder
	}
	return r.Services.Category.Create(ctx, input.BranchID, input.Name, description, sortOrder)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, name *string, description *string, sortOrder *int, isActive *bool) (*model.Category, error) {
	return r.Services.Category.Update(ctx, id, name, description, sortOrder, isActive)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.Services.Category.Delete(ctx, id)
	return err == nil, err
}

// ReorderCategories is the resolver for the reorderCategories field.
func (r *mutationResolver) ReorderCategories(ctx context.Context, branchID uuid.UUID, categoryIds []uuid.UUID) ([]model.Category, error) {
	cats, err := r.Services.Category.Reorder(ctx, branchID, categoryIds)
	if err != nil {
		return nil, err
	}
	result := make([]model.Category, len(cats))
	for i, c := range cats {
		result[i] = *c
	}
	return result, nil
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input CreateProductInput) (*model.Product, error) {
	return r.Services.Product.Create(ctx, serviceCreateProductInput(input))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input CreateProductInput) (*model.Product, error) {
	return r.Services.Product.Update(ctx, id, serviceCreateProductInput(input))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.Services.Product.Delete(ctx, id)
	return err == nil, err
}

// ToggleProductAvailability is the resolver for the toggleProductAvailability field.
// FIX: removed isAvailable parameter - schema toggles, doesn't set
func (r *mutationResolver) ToggleProductAvailability(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	return r.Services.Product.ToggleAvailability(ctx, id)
}

// CreateTable is the resolver for the createTable field.
func (r *mutationResolver) CreateTable(ctx context.Context, input CreateTableInput) (*Table, error) {
	capacity := 4
	if input.Capacity != nil {
		capacity = *input.Capacity
	}
	return r.Services.Table.Create(ctx, input.BranchID, input.Number, capacity)
}

// UpdateTable is the resolver for the updateTable field.
func (r *mutationResolver) UpdateTable(ctx context.Context, id uuid.UUID, number *string, capacity *int) (*Table, error) {
	existing, err := r.Services.Table.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	num := existing.Number
	cap := existing.Capacity
	if number != nil {
		num = *number
	}
	if capacity != nil {
		cap = *capacity
	}
	return r.Services.Table.Update(ctx, id, num, cap)
}

// DeleteTable is the resolver for the deleteTable field.
func (r *mutationResolver) DeleteTable(ctx context.Context, id uuid.UUID) (bool, error) {
	err := r.Services.Table.Delete(ctx, id)
	return err == nil, err
}

// UpdateTableStatus is the resolver for the updateTableStatus field.
func (r *mutationResolver) UpdateTableStatus(ctx context.Context, id uuid.UUID, status model.TableStatus) (*Table, error) {
	err := r.Services.Table.UpdateStatus(ctx, id, status)
	if err != nil {
		return nil, err
	}
	return r.Services.Table.GetByID(ctx, id)
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input CreateOrderInput) (*model.Order, error) {
	items := make([]struct {
		ProductID uuid.UUID
		Quantity  int
		Notes     *string
	}, len(input.Items))
	for i, item := range input.Items {
		items[i] = struct {
			ProductID uuid.UUID
			Quantity  int
			Notes     *string
		}{item.ProductID, item.Quantity, item.Notes}
	}
	order, err := r.Services.Order.Create(ctx, struct {
		BranchID      uuid.UUID
		TableID       *uuid.UUID
		UserID        uuid.UUID
		CustomerName  *string
		CustomerPhone *string
		Notes         *string
		Items         []struct {
			ProductID uuid.UUID
			Quantity  int
			Notes     *string
		}
	}{input.BranchID, input.TableID, input.UserID, input.CustomerName, input.CustomerPhone, input.Notes, items})
	if err != nil {
		return nil, err
	}

	// Notify kitchen staff about new order
	go func() {
		tableName := "Mostrador"
		if input.TableID != nil {
			if table, err := r.Services.Table.GetByID(context.Background(), *input.TableID); err == nil {
				tableName = table.Number
			}
		}
		r.Services.FCM.NotifyNewOrder(context.Background(), input.BranchID, order.ID, tableName, len(items))
	}()

	return order, nil
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id uuid.UUID, status model.OrderStatus) (*model.Order, error) {
	err := r.Services.Order.UpdateStatus(ctx, id, status)
	if err != nil {
		return nil, err
	}
	order, err := r.Services.Order.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}

	// Trigger notifications based on status change
	if status == model.OrderReady {
		// Notify waiter when order is ready
		go func() {
			tableName := "Mostrador"
			if order.TableID != nil {
				if table, err := r.Services.Table.GetByID(context.Background(), *order.TableID); err == nil {
					tableName = table.Number
				}
			}
			r.Services.FCM.NotifyOrderReady(context.Background(), order.ID, order.UserID, tableName)
		}()
	}

	return order, nil
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	err := r.Services.Order.Cancel(ctx, id)
	if err != nil {
		return nil, err
	}
	return r.Services.Order.GetByID(ctx, id)
}

// AddOrderItem is the resolver for the addOrderItem field.
func (r *mutationResolver) AddOrderItem(ctx context.Context, orderID uuid.UUID, input CreateOrderItemInput) (*model.OrderItem, error) {
	return r.Services.Order.AddItem(ctx, orderID, AddItemInput{
		ProductID: input.ProductID,
		Quantity:  input.Quantity,
		Notes:     input.Notes,
	})
}

// RemoveOrderItem is the resolver for the removeOrderItem field.
// FIX: Return type changed from (bool, error) to (*model.Order, error)
func (r *mutationResolver) RemoveOrderItem(ctx context.Context, orderID uuid.UUID, itemID uuid.UUID) (*model.Order, error) {
	item, err := r.Services.Order.GetItem(ctx, itemID)
	if err != nil {
		return nil, err
	}
	order, err := r.Services.Order.RemoveItem(ctx, item.OrderID, itemID)
	if err != nil {
		return nil, err
	}
	return order, nil
}

// CreateReservation is the resolver for the createReservation field.
func (r *mutationResolver) CreateReservation(ctx context.Context, input CreateReservationInput) (*model.Reservation, error) {
	reservation, err := r.Services.Reservation.Create(ctx, serviceReservationInput(input))
	if err != nil {
		return nil, err
	}

	// Notify managers about new reservation
	go func() {
		r.Services.FCM.NotifyNewReservation(
			context.Background(),
			input.BranchID,
			reservation.ID,
			input.CustomerName,
			input.GuestCount,
			input.ReservationTime,
		)
	}()

	return reservation, nil
}

// UpdateReservation is the resolver for the updateReservation field.
func (r *mutationResolver) UpdateReservation(ctx context.Context, id uuid.UUID, input CreateReservationInput) (*model.Reservation, error) {
	return r.Services.Reservation.Update(ctx, id, serviceReservationInput(input))
}

// CancelReservation is the resolver for the cancelReservation field.
func (r *mutationResolver) CancelReservation(ctx context.Context, id uuid.UUID) (*model.Reservation, error) {
	err := r.Services.Reservation.Cancel(ctx, id)
	if err != nil {
		return nil, err
	}
	return r.Services.Reservation.GetByID(ctx, id)
}

// Branch is the resolver for the branch field.
func (r *orderResolver) Branch(ctx context.Context, obj *model.Order) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, obj.BranchID)
}

// Table is the resolver for the table field.
func (r *orderResolver) Table(ctx context.Context, obj *model.Order) (*Table, error) {
	if obj.TableID == nil {
		return nil, nil
	}
	return r.Services.Table.GetByID(ctx, *obj.TableID)
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	return r.Services.User.GetByID(ctx, obj.UserID)
}

// Items is the resolver for the items field.
func (r *orderResolver) Items(ctx context.Context, obj *model.Order) ([]model.OrderItem, error) {
	return r.Services.Order.GetItems(ctx, obj.ID)
}

// Order is the resolver for the order field.
func (r *orderItemResolver) Order(ctx context.Context, obj *model.OrderItem) (*model.Order, error) {
	return r.Services.Order.GetByID(ctx, obj.OrderID)
}

// Product is the resolver for the product field.
func (r *orderItemResolver) Product(ctx context.Context, obj *model.OrderItem) (*model.Product, error) {
	return r.Services.Product.GetByID(ctx, obj.ProductID)
}

// Branch is the resolver for the branch field.
func (r *productResolver) Branch(ctx context.Context, obj *model.Product) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, obj.BranchID)
}

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *model.Product) (*model.Category, error) {
	if obj.CategoryID == nil {
		return nil, nil
	}
	return r.Services.Category.GetByID(ctx, *obj.CategoryID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, err := GetUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.Services.User.GetByID(ctx, userID)
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context) (*model.Tenant, error) {
	tenantID, err := GetTenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.Services.Tenant.GetByID(ctx, tenantID)
}

// Branches is the resolver for the branches field.
func (r *queryResolver) Branches(ctx context.Context) ([]model.Branch, error) {
	tenantID, err := GetTenantIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	return r.Services.Branch.GetByTenant(ctx, tenantID)
}

// Branch is the resolver for the branch field.
func (r *queryResolver) Branch(ctx context.Context, id uuid.UUID) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, id)
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, branchID uuid.UUID) ([]model.User, error) {
	return r.Services.User.GetByBranch(ctx, branchID)
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	return r.Services.User.GetByID(ctx, id)
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, branchID uuid.UUID) ([]model.Category, error) {
	return r.Services.Category.GetByBranch(ctx, branchID)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*model.Category, error) {
	return r.Services.Category.GetByID(ctx, id)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, branchID uuid.UUID, categoryID *uuid.UUID) ([]model.Product, error) {
	if categoryID != nil {
		return r.Services.Product.GetByCategory(ctx, branchID, *categoryID)
	}
	return r.Services.Product.GetByBranchAll(ctx, branchID)
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	return r.Services.Product.GetByID(ctx, id)
}

// FeaturedProducts is the resolver for the featuredProducts field.
func (r *queryResolver) FeaturedProducts(ctx context.Context, branchID uuid.UUID) ([]model.Product, error) {
	return r.Services.Product.GetFeatured(ctx, branchID)
}

// Tables is the resolver for the tables field.
func (r *queryResolver) Tables(ctx context.Context, branchID uuid.UUID) ([]Table, error) {
	return r.Services.Table.GetByBranch(ctx, branchID)
}

// Table is the resolver for the table field.
func (r *queryResolver) Table(ctx context.Context, id uuid.UUID) (*Table, error) {
	return r.Services.Table.GetByID(ctx, id)
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, branchID uuid.UUID, status *model.OrderStatus, limit *int) ([]model.Order, error) {
	orders, err := r.Services.Order.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}
	if status != nil {
		filtered := make([]model.Order, 0)
		for _, o := range orders {
			if o.Status == *status {
				filtered = append(filtered, o)
			}
		}
		orders = filtered
	}
	if limit != nil && len(orders) > *limit {
		orders = orders[:*limit]
	}
	return orders, nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	return r.Services.Order.GetByID(ctx, id)
}

// ActiveOrders is the resolver for the activeOrders field.
func (r *queryResolver) ActiveOrders(ctx context.Context, branchID uuid.UUID) ([]model.Order, error) {
	orders, err := r.Services.Order.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}
	active := []model.Order{}
	for _, o := range orders {
		if o.Status != model.OrderDelivered && o.Status != model.OrderCancelled && o.Status != model.OrderPaid {
			active = append(active, o)
		}
	}
	return active, nil
}

// Reservations is the resolver for the reservations field.
func (r *queryResolver) Reservations(ctx context.Context, branchID uuid.UUID, date *string) ([]model.Reservation, error) {
	if date != nil {
		t, err := time.Parse("2006-01-02", *date)
		if err != nil {
			return nil, err
		}
		return r.Services.Reservation.GetByDate(ctx, branchID, t)
	}
	return r.Services.Reservation.GetByBranch(ctx, branchID)
}

// Reservation is the resolver for the reservation field.
func (r *queryResolver) Reservation(ctx context.Context, id uuid.UUID) (*model.Reservation, error) {
	return r.Services.Reservation.GetByID(ctx, id)
}

// DashboardMetrics is the resolver for the dashboardMetrics field.
func (r *queryResolver) DashboardMetrics(ctx context.Context, branchID uuid.UUID, period string) (*DashboardMetrics, error) {
	metrics, err := r.Services.Analytics.GetDashboardMetrics(ctx, branchID)
	if err != nil {
		return nil, err
	}

	topProds, err := r.Services.Analytics.GetTopProducts(ctx, branchID, 10)
	if err != nil {
		topProds = []TopProduct{}
	}

	var topProducts []TopProduct
	for _, p := range topProds {
		topProducts = append(topProducts, TopProduct{
			ProductID:    p.ProductID,
			ProductName:  p.ProductName,
			QuantitySold: p.QuantitySold,
			Revenue:      p.Revenue,
		})
	}

	// Get sales by day for the last 7 days
	dailySales, _ := r.Services.Analytics.GetSalesByDay(ctx, branchID, 7)
	var dailySalesResult []DailySales
	for _, ds := range dailySales {
		dailySalesResult = append(dailySalesResult, DailySales{
			Date:    ds.Date,
			Revenue: ds.Revenue,
			Orders:  ds.Orders,
		})
	}

	return &DashboardMetrics{
		TotalRevenue:     metrics.TotalRevenue,
		TodayRevenue:     metrics.TodayRevenue,
		WeekRevenue:      metrics.WeekRevenue,
		MonthRevenue:     metrics.MonthRevenue,
		TotalOrders:      metrics.TotalOrders,
		OrdersToday:      metrics.OrdersToday,
		OrdersThisWeek:   metrics.OrdersThisWeek,
		OrdersThisMonth:  metrics.OrdersThisMonth,
		AverageTicket:    metrics.AverageTicket,
		ActiveOrders:     metrics.ActiveOrders,
		TotalTables:      metrics.TotalTables,
		AvailableTables: metrics.AvailableTables,
		TopProducts:      topProducts,
		DailySales:       dailySalesResult,
	}, nil
}

// TopProducts is the resolver for the topProducts field.
func (r *queryResolver) TopProducts(ctx context.Context, branchID uuid.UUID, limit *int, period *string) ([]TopProduct, error) {
	limitVal := 10
	if limit != nil {
		limitVal = *limit
	}

	products, err := r.Services.Analytics.GetTopProducts(ctx, branchID, limitVal)
	if err != nil {
		return nil, err
	}

	var result []TopProduct
	for _, p := range products {
		result = append(result, TopProduct{
			ProductID:    p.ProductID,
			ProductName:  p.ProductName,
			QuantitySold: p.QuantitySold,
			Revenue:      p.Revenue,
		})
	}
	return result, nil
}

// SalesByDay is the resolver for the salesByDay field.
func (r *queryResolver) SalesByDay(ctx context.Context, branchID uuid.UUID, days int) ([]DailySales, error) {
	sales, err := r.Services.Analytics.GetSalesByDay(ctx, branchID, days)
	if err != nil {
		return nil, err
	}
	var result []DailySales
	for _, s := range sales {
		result = append(result, DailySales{
			Date:    s.Date,
			Orders:  s.Orders,
			Revenue: s.Revenue,
		})
	}
	return result, nil
}

// OrdersByStatus is the resolver for the ordersByStatus field.
func (r *queryResolver) OrdersByStatus(ctx context.Context, branchID uuid.UUID) ([]StatusCount, error) {
	statusCounts, err := r.Services.Analytics.GetOrdersByStatus(ctx, branchID)
	if err != nil {
		return nil, err
	}
	var result []StatusCount
	for _, sc := range statusCounts {
		result = append(result, StatusCount{Status: sc.Status, Count: sc.Count})
	}
	return result, nil
}

// RevenueByPeriod is the resolver for the revenueByPeriod field.
func (r *queryResolver) RevenueByPeriod(ctx context.Context, branchID uuid.UUID, period string) (*RevenueReport, error) {
	report, err := r.Services.Analytics.GetRevenueByPeriod(ctx, branchID, period)
	if err != nil {
		return nil, err
	}

	var byStatus []StatusCount
	for _, s := range report.ByStatus {
		byStatus = append(byStatus, StatusCount{Status: s.Status, Count: s.Count})
	}

	var dailySales []DailySales
	for _, d := range report.DailySales {
		dailySales = append(dailySales, DailySales{
			Date:    d.Date,
			Orders:  d.Orders,
			Revenue: d.Revenue,
		})
	}

	return &RevenueReport{
		Period:          report.Period,
		TotalRevenue:    report.TotalRevenue,
		TotalOrders:     report.TotalOrders,
		AverageTicket:   report.AverageTicket,
		ByStatus:        byStatus,
		ByPaymentMethod: []PaymentMethodRevenue{},
		DailySales:     dailySales,
	}, nil
}

// Branch is the resolver for the branch field.
func (r *reservationResolver) Branch(ctx context.Context, obj *model.Reservation) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, obj.BranchID)
}

// Table is the resolver for the table field.
func (r *reservationResolver) Table(ctx context.Context, obj *model.Reservation) (*Table, error) {
	if obj.TableID == nil {
		return nil, nil
	}
	return r.Services.Table.GetByID(ctx, *obj.TableID)
}

// ReservationDate is the resolver for the reservationDate field.
func (r *reservationResolver) ReservationDate(ctx context.Context, obj *model.Reservation) (string, error) {
	return obj.ReservationDate.Format("2006-01-02"), nil
}

// ReservationTime is the resolver for the reservationTime field.
func (r *reservationResolver) ReservationTime(ctx context.Context, obj *model.Reservation) (*time.Time, error) {
	t, err := time.Parse("15:04:05", obj.ReservationTime)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// Branches is the resolver for the branches field.
func (r *tenantResolver) Branches(ctx context.Context, obj *model.Tenant) ([]model.Branch, error) {
	return r.Services.Branch.GetByTenant(ctx, obj.ID)
}

// Branch is the resolver for the branch field.
func (r *userResolver) Branch(ctx context.Context, obj *model.User) (*model.Branch, error) {
	return r.Services.Branch.GetByID(ctx, obj.BranchID)
}

// Branch returns BranchResolver implementation.
func (r *Resolver) Branch() BranchResolver { return &branchResolver{r} }

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Reservation returns ReservationResolver implementation.
func (r *Resolver) Reservation() ReservationResolver { return &reservationResolver{r} }

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type branchResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reservationResolver struct{ *Resolver }
type tenantResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// ============ Helper Functions ============

// convertTablesToGraphQL converts model.RestaurantTable to graph.Table
func convertTablesToGraphQL(tables []model.RestaurantTable, err error) ([]Table, error) {
	if err != nil {
		return nil, err
	}
	result := make([]Table, len(tables))
	for i, t := range tables {
		result[i] = Table{
			ID:        t.ID,
			BranchID:  t.BranchID,
			Number:    t.Number,
			Capacity:  t.Capacity,
			Status:    t.Status,
			CreatedAt: t.CreatedAt,
			UpdatedAt: t.UpdatedAt,
		}
	}
	return result, nil
}

// serviceCreateProductInput converts CreateProductInput to service.CreateProductInput
func serviceCreateProductInput(input CreateProductInput) service.CreateProductInput {
	result := service.CreateProductInput{
		BranchID:  input.BranchID,
		Name:      input.Name,
		Price:     input.Price,
		Allergens: []string{},
	}
	if input.CategoryID != nil {
		result.CategoryID = input.CategoryID
	}
	if input.Description != nil {
		result.Description = input.Description
	}
	if input.ImageURL != nil {
		result.ImageURL = input.ImageURL
	}
	if input.IsAvailable != nil {
		result.IsAvailable = input.IsAvailable
	}
	if input.IsFeatured != nil {
		result.IsFeatured = input.IsFeatured
	}
	if input.PreparationTime != nil {
		result.PreparationTime = input.PreparationTime
	}
	if input.Allergens != nil {
		result.Allergens = input.Allergens
	}
	return result
}

// serviceReservationInput converts CreateReservationInput to service.CreateReservationInput
func serviceReservationInput(input CreateReservationInput) service.CreateReservationInput {
	result := service.CreateReservationInput{
		BranchID:    input.BranchID,
		CustomerName: input.CustomerName,
		GuestCount:  input.GuestCount,
		ReservationDate: input.ReservationDate.Format("2006-01-02"),
		ReservationTime: input.ReservationTime,
	}
	if input.TableID != nil {
		result.TableID = input.TableID
	}
	if input.CustomerPhone != nil {
		result.CustomerPhone = input.CustomerPhone
	}
	if input.CustomerEmail != nil {
		result.CustomerEmail = input.CustomerEmail
	}
	if input.Notes != nil {
		result.Notes = input.Notes
	}
	return result
}
