package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/greenpos/backend/internal/model"
)

func intPtr(i int) *int {
	return &i
}

// Tenant is the resolver for the tenant field.
func (r *branchResolver) Tenant(ctx context.Context, obj *model.Branch) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: Tenant - tenant"))
}

// Users is the resolver for the users field.
func (r *branchResolver) Users(ctx context.Context, obj *model.Branch) ([]model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// Categories is the resolver for the categories field.
func (r *branchResolver) Categories(ctx context.Context, obj *model.Branch) ([]model.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Products is the resolver for the products field.
func (r *branchResolver) Products(ctx context.Context, obj *model.Branch) ([]model.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Tables is the resolver for the tables field.
func (r *branchResolver) Tables(ctx context.Context, obj *model.Branch) ([]Table, error) {
	panic(fmt.Errorf("not implemented: Tables - tables"))
}

// Orders is the resolver for the orders field.
func (r *branchResolver) Orders(ctx context.Context, obj *model.Branch) ([]model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Reservations is the resolver for the reservations field.
func (r *branchResolver) Reservations(ctx context.Context, obj *model.Branch) ([]model.Reservation, error) {
	panic(fmt.Errorf("not implemented: Reservations - reservations"))
}

// Branch is the resolver for the branch field.
func (r *categoryResolver) Branch(ctx context.Context, obj *model.Category) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Products is the resolver for the products field.
func (r *categoryResolver) Products(ctx context.Context, obj *model.Category) ([]model.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, email string, password string, branchID uuid.UUID) (*AuthPayload, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// CreateTenant is the resolver for the createTenant field.
func (r *mutationResolver) CreateTenant(ctx context.Context, input CreateTenantInput) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: CreateTenant - createTenant"))
}

// UpdateTenant is the resolver for the updateTenant field.
func (r *mutationResolver) UpdateTenant(ctx context.Context, id uuid.UUID, name *string, settings model.JSON) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: UpdateTenant - updateTenant"))
}

// CreateBranch is the resolver for the createBranch field.
func (r *mutationResolver) CreateBranch(ctx context.Context, input CreateBranchInput) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: CreateBranch - createBranch"))
}

// UpdateBranch is the resolver for the updateBranch field.
func (r *mutationResolver) UpdateBranch(ctx context.Context, id uuid.UUID, name *string, address *string, phone *string) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: UpdateBranch - updateBranch"))
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input CreateUserInput) (*model.User, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id uuid.UUID, name *string, role *model.UserRole, isActive *bool) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUser - updateUser"))
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteUser - deleteUser"))
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input CreateCategoryInput) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: CreateCategory - createCategory"))
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uuid.UUID, name *string, description *string, sortOrder *int, isActive *bool) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: UpdateCategory - updateCategory"))
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteCategory - deleteCategory"))
}

// ReorderCategories is the resolver for the reorderCategories field.
func (r *mutationResolver) ReorderCategories(ctx context.Context, branchID uuid.UUID, categoryIds []uuid.UUID) ([]model.Category, error) {
	panic(fmt.Errorf("not implemented: ReorderCategories - reorderCategories"))
}

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input CreateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateProduct is the resolver for the updateProduct field.
func (r *mutationResolver) UpdateProduct(ctx context.Context, id uuid.UUID, input CreateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: UpdateProduct - updateProduct"))
}

// DeleteProduct is the resolver for the deleteProduct field.
func (r *mutationResolver) DeleteProduct(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteProduct - deleteProduct"))
}

// ToggleProductAvailability is the resolver for the toggleProductAvailability field.
func (r *mutationResolver) ToggleProductAvailability(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: ToggleProductAvailability - toggleProductAvailability"))
}

// CreateTable is the resolver for the createTable field.
func (r *mutationResolver) CreateTable(ctx context.Context, input CreateTableInput) (*Table, error) {
	panic(fmt.Errorf("not implemented: CreateTable - createTable"))
}

// UpdateTable is the resolver for the updateTable field.
func (r *mutationResolver) UpdateTable(ctx context.Context, id uuid.UUID, number *string, capacity *int) (*Table, error) {
	panic(fmt.Errorf("not implemented: UpdateTable - updateTable"))
}

// DeleteTable is the resolver for the deleteTable field.
func (r *mutationResolver) DeleteTable(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteTable - deleteTable"))
}

// UpdateTableStatus is the resolver for the updateTableStatus field.
func (r *mutationResolver) UpdateTableStatus(ctx context.Context, id uuid.UUID, status model.TableStatus) (*Table, error) {
	panic(fmt.Errorf("not implemented: UpdateTableStatus - updateTableStatus"))
}

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input CreateOrderInput) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CreateOrder - createOrder"))
}

// UpdateOrderStatus is the resolver for the updateOrderStatus field.
func (r *mutationResolver) UpdateOrderStatus(ctx context.Context, id uuid.UUID, status model.OrderStatus) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: UpdateOrderStatus - updateOrderStatus"))
}

// CancelOrder is the resolver for the cancelOrder field.
func (r *mutationResolver) CancelOrder(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: CancelOrder - cancelOrder"))
}

// AddOrderItem is the resolver for the addOrderItem field.
func (r *mutationResolver) AddOrderItem(ctx context.Context, orderID uuid.UUID, input CreateOrderItemInput) (*model.OrderItem, error) {
	panic(fmt.Errorf("not implemented: AddOrderItem - addOrderItem"))
}

// RemoveOrderItem is the resolver for the removeOrderItem field.
func (r *mutationResolver) RemoveOrderItem(ctx context.Context, id uuid.UUID) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveOrderItem - removeOrderItem"))
}

// CreateReservation is the resolver for the createReservation field.
func (r *mutationResolver) CreateReservation(ctx context.Context, input CreateReservationInput) (*model.Reservation, error) {
	panic(fmt.Errorf("not implemented: CreateReservation - createReservation"))
}

// UpdateReservation is the resolver for the updateReservation field.
func (r *mutationResolver) UpdateReservation(ctx context.Context, id uuid.UUID, input CreateReservationInput) (*model.Reservation, error) {
	panic(fmt.Errorf("not implemented: UpdateReservation - updateReservation"))
}

// CancelReservation is the resolver for the cancelReservation field.
func (r *mutationResolver) CancelReservation(ctx context.Context, id uuid.UUID) (*model.Reservation, error) {
	panic(fmt.Errorf("not implemented: CancelReservation - cancelReservation"))
}

// Branch is the resolver for the branch field.
func (r *orderResolver) Branch(ctx context.Context, obj *model.Order) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Table is the resolver for the table field.
func (r *orderResolver) Table(ctx context.Context, obj *model.Order) (*Table, error) {
	panic(fmt.Errorf("not implemented: Table - table"))
}

// User is the resolver for the user field.
func (r *orderResolver) User(ctx context.Context, obj *model.Order) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Items is the resolver for the items field.
func (r *orderResolver) Items(ctx context.Context, obj *model.Order) ([]model.OrderItem, error) {
	panic(fmt.Errorf("not implemented: Items - items"))
}

// Order is the resolver for the order field.
func (r *orderItemResolver) Order(ctx context.Context, obj *model.OrderItem) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// Product is the resolver for the product field.
func (r *orderItemResolver) Product(ctx context.Context, obj *model.OrderItem) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// Branch is the resolver for the branch field.
func (r *productResolver) Branch(ctx context.Context, obj *model.Product) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Category is the resolver for the category field.
func (r *productResolver) Category(ctx context.Context, obj *model.Product) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	panic(fmt.Errorf("not implemented: Me - me"))
}

// Tenant is the resolver for the tenant field.
func (r *queryResolver) Tenant(ctx context.Context) (*model.Tenant, error) {
	panic(fmt.Errorf("not implemented: Tenant - tenant"))
}

// Branches is the resolver for the branches field.
func (r *queryResolver) Branches(ctx context.Context) ([]model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branches - branches"))
}

// Branch is the resolver for the branch field.
func (r *queryResolver) Branch(ctx context.Context, id uuid.UUID) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, branchID uuid.UUID) ([]model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uuid.UUID) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Categories is the resolver for the categories field.
func (r *queryResolver) Categories(ctx context.Context, branchID uuid.UUID) ([]model.Category, error) {
	panic(fmt.Errorf("not implemented: Categories - categories"))
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uuid.UUID) (*model.Category, error) {
	panic(fmt.Errorf("not implemented: Category - category"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, branchID uuid.UUID, categoryID *uuid.UUID) ([]model.Product, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id uuid.UUID) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// FeaturedProducts is the resolver for the featuredProducts field.
func (r *queryResolver) FeaturedProducts(ctx context.Context, branchID uuid.UUID) ([]model.Product, error) {
	panic(fmt.Errorf("not implemented: FeaturedProducts - featuredProducts"))
}

// Tables is the resolver for the tables field.
func (r *queryResolver) Tables(ctx context.Context, branchID uuid.UUID) ([]Table, error) {
	panic(fmt.Errorf("not implemented: Tables - tables"))
}

// Table is the resolver for the table field.
func (r *queryResolver) Table(ctx context.Context, id uuid.UUID) (*Table, error) {
	panic(fmt.Errorf("not implemented: Table - table"))
}

// Orders is the resolver for the orders field.
func (r *queryResolver) Orders(ctx context.Context, branchID uuid.UUID, status *model.OrderStatus, limit *int) ([]model.Order, error) {
	panic(fmt.Errorf("not implemented: Orders - orders"))
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, id uuid.UUID) (*model.Order, error) {
	panic(fmt.Errorf("not implemented: Order - order"))
}

// ActiveOrders is the resolver for the activeOrders field.
func (r *queryResolver) ActiveOrders(ctx context.Context, branchID uuid.UUID) ([]model.Order, error) {
	panic(fmt.Errorf("not implemented: ActiveOrders - activeOrders"))
}

// Reservations is the resolver for the reservations field.
func (r *queryResolver) Reservations(ctx context.Context, branchID uuid.UUID, date *string) ([]model.Reservation, error) {
	panic(fmt.Errorf("not implemented: Reservations - reservations"))
}

// Reservation is the resolver for the reservation field.
func (r *queryResolver) Reservation(ctx context.Context, id uuid.UUID) (*model.Reservation, error) {
	panic(fmt.Errorf("not implemented: Reservation - reservation"))
}

// DashboardMetrics is the resolver for the dashboardMetrics field.
func (r *queryResolver) DashboardMetrics(ctx context.Context, branchID uuid.UUID, period string) (*DashboardMetrics, error) {
	// Get all orders for the branch
	orders, err := r.Services.Order.Orders.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}

	now := time.Now()
	today := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())
	weekAgo := today.AddDate(0, 0, -7)

	var totalOrders, ordersToday, ordersThisWeek int
	var totalRevenue, revenueToday, revenueThisWeek float64
	statusCounts := make(map[string]int)

	for _, order := range orders {
		if order.Status == model.OrderPaid || order.Status == model.OrderDelivered {
			totalOrders++
			totalRevenue += order.Total

			if order.CreatedAt.After(today) {
				ordersToday++
				revenueToday += order.Total
			}
			if order.CreatedAt.After(weekAgo) {
				ordersThisWeek++
				revenueThisWeek += order.Total
			}
		}
		statusCounts[string(order.Status)]++
	}

	avgTicket := float64(0)
	if totalOrders > 0 {
		avgTicket = totalRevenue / float64(totalOrders)
	}

	// Get top products
	topProds, _ := r.TopProducts(ctx, branchID, intPtr(5), nil)

	return &DashboardMetrics{
		TotalOrders:    totalOrders,
		TotalRevenue:   totalRevenue,
		AverageTicket:  avgTicket,
		OrdersToday:    ordersToday,
		RevenueToday:   revenueToday,
		OrdersThisWeek: ordersThisWeek,
		RevenueThisWeek: revenueThisWeek,
		TopProducts:    topProds,
	}, nil
}

// TopProducts is the resolver for the topProducts field.
func (r *queryResolver) TopProducts(ctx context.Context, branchID uuid.UUID, limit *int, period *string) ([]TopProduct, error) {
	limitVal := 10
	if limit != nil {
		limitVal = *limit
	}

	orders, err := r.Services.Order.Orders.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}

	// Aggregate sales by product
	productSales := make(map[string]struct {
		name    string
		qty     int
		revenue float64
	})

	for _, order := range orders {
		if order.Status != model.OrderPaid && order.Status != model.OrderDelivered {
			continue
		}
		items, err := r.Services.Order.Orders.GetItems(ctx, order.ID)
		if err != nil {
			continue
		}
		for _, item := range items {
			prod, _ := r.Services.Product.Products.GetByID(ctx, item.ProductID)
			name := "Unknown"
			if prod != nil {
				name = prod.Name
			}
			key := item.ProductID.String()
			if existing, ok := productSales[key]; ok {
				productSales[key] = struct {
					name    string
					qty     int
					revenue float64
				}{name: name, qty: existing.qty + int(item.Quantity), revenue: existing.revenue + item.TotalPrice}
			} else {
				productSales[key] = struct {
					name    string
					qty     int
					revenue float64
				}{name: name, qty: int(item.Quantity), revenue: item.TotalPrice}
			}
		}
	}

	// Sort and limit
	type productSale struct {
		id       string
		name     string
		qty      int
		revenue  float64
	}
	var sorted []productSale
	for id, ps := range productSales {
		sorted = append(sorted, productSale{id: id, name: ps.name, qty: ps.qty, revenue: ps.revenue})
	}
	// Simple sort by revenue
	for i := 0; i < len(sorted)-1; i++ {
		for j := i + 1; j < len(sorted); j++ {
			if sorted[j].revenue > sorted[i].revenue {
				sorted[i], sorted[j] = sorted[j], sorted[i]
			}
		}
	}
	if limitVal > len(sorted) {
		limitVal = len(sorted)
	}

	var result []TopProduct
	for i := 0; i < limitVal; i++ {
		result = append(result, TopProduct{
			ProductID:     sorted[i].id,
			ProductName:   sorted[i].name,
			QuantitySold:  sorted[i].qty,
			Revenue:       sorted[i].revenue,
		})
	}
	return result, nil
}

// SalesByDay is the resolver for the salesByDay field.
func (r *queryResolver) SalesByDay(ctx context.Context, branchID uuid.UUID, days int) ([]DailySales, error) {
	orders, err := r.Services.Order.Orders.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}

	now := time.Now()
	result := make([]DailySales, days)

	for i := days - 1; i >= 0; i-- {
		date := now.AddDate(0, 0, -i)
		dayStart := time.Date(date.Year(), date.Month(), date.Day(), 0, 0, 0, 0, date.Location())
		dayEnd := dayStart.AddDate(0, 0, 1)

		var dayOrders int
		var dayRevenue float64
		for _, order := range orders {
			if (order.Status == model.OrderPaid || order.Status == model.OrderDelivered) &&
				order.CreatedAt.After(dayStart) && order.CreatedAt.Before(dayEnd) {
				dayOrders++
				dayRevenue += order.Total
			}
		}
		result[days-1-i] = DailySales{
			Date:    dayStart.Format("2006-01-02"),
			Orders:  dayOrders,
			Revenue: dayRevenue,
		}
	}
	return result, nil
}

// OrdersByStatus is the resolver for the ordersByStatus field.
func (r *queryResolver) OrdersByStatus(ctx context.Context, branchID uuid.UUID) ([]StatusCount, error) {
	orders, err := r.Services.Order.Orders.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}

	counts := make(map[string]int)
	for _, order := range orders {
		counts[string(order.Status)]++
	}

	var result []StatusCount
	for status, count := range counts {
		result = append(result, StatusCount{
			Status: status,
			Count:  count,
		})
	}
	return result, nil
}

// RevenueByPeriod is the resolver for the revenueByPeriod field.
func (r *queryResolver) RevenueByPeriod(ctx context.Context, branchID uuid.UUID, period string) (*RevenueReport, error) {
	orders, err := r.Services.Order.Orders.GetByBranch(ctx, branchID)
	if err != nil {
		return nil, err
	}

	var totalOrders int
	var totalRevenue float64

	for _, order := range orders {
		if order.Status == model.OrderPaid || order.Status == model.OrderDelivered {
			totalOrders++
			totalRevenue += order.Total
		}
	}

	avgTicket := float64(0)
	if totalOrders > 0 {
		avgTicket = totalRevenue / float64(totalOrders)
	}

	return &RevenueReport{
		Period:        period,
		TotalRevenue:  totalRevenue,
		TotalOrders:   totalOrders,
		AverageTicket: avgTicket,
		ByPaymentMethod: []PaymentMethodRevenue{}, // Payment method tracking not implemented
	}, nil
}

// Branch is the resolver for the branch field.
func (r *reservationResolver) Branch(ctx context.Context, obj *model.Reservation) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Table is the resolver for the table field.
func (r *reservationResolver) Table(ctx context.Context, obj *model.Reservation) (*Table, error) {
	panic(fmt.Errorf("not implemented: Table - table"))
}

// ReservationDate is the resolver for the reservationDate field.
func (r *reservationResolver) ReservationDate(ctx context.Context, obj *model.Reservation) (string, error) {
	panic(fmt.Errorf("not implemented: ReservationDate - reservationDate"))
}

// ReservationTime is the resolver for the reservationTime field.
func (r *reservationResolver) ReservationTime(ctx context.Context, obj *model.Reservation) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: ReservationTime - reservationTime"))
}

// Branches is the resolver for the branches field.
func (r *tenantResolver) Branches(ctx context.Context, obj *model.Tenant) ([]model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branches - branches"))
}

// Branch is the resolver for the branch field.
func (r *userResolver) Branch(ctx context.Context, obj *model.User) (*model.Branch, error) {
	panic(fmt.Errorf("not implemented: Branch - branch"))
}

// Branch returns BranchResolver implementation.
func (r *Resolver) Branch() BranchResolver { return &branchResolver{r} }

// Category returns CategoryResolver implementation.
func (r *Resolver) Category() CategoryResolver { return &categoryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Order returns OrderResolver implementation.
func (r *Resolver) Order() OrderResolver { return &orderResolver{r} }

// OrderItem returns OrderItemResolver implementation.
func (r *Resolver) OrderItem() OrderItemResolver { return &orderItemResolver{r} }

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Reservation returns ReservationResolver implementation.
func (r *Resolver) Reservation() ReservationResolver { return &reservationResolver{r} }

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type branchResolver struct{ *Resolver }
type categoryResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type orderResolver struct{ *Resolver }
type orderItemResolver struct{ *Resolver }
type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type reservationResolver struct{ *Resolver }
type tenantResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
